#! /bin/sh

if [ -x $HOME/.local/bin/dual_monitor ];then
  dual_monitor
fi


pgrep -x sxhkd >/dev/null || sxhkd &
bspc monitor eDP -d 1 2 3 4 5 &
bspc monitor DisplayPort-0 -d 6 7 8 9  &

xautolock -time 5 -locker "daos /sbin/zzz" -detectsleep
pgrep bspswallow || bspswallow &
xwallpaper --zoom ~/.config/wall.jpg &
$HOME/.config/polybar/launch.sh


bspc config window_gap 10
bspc config border_width 2
bspc config normal_border_color "#32344a"
bspc config focused_border_color "#787c99"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

