#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
bspc monitor eDP -d 1 2 3 4 5 &
bspc monitor DisplayPort-0 -d 1 2 3 4 5 &
xautolock -time 5 -locker "sudo /sbin/zzz" -detectsleep
pgrep bspswallow || bspswallow &
xwallpaper --zoom ~/.config/wall.jpg &
$HOME/.config/polybar/launch.sh


bspc config window_gap 10
bspc config border_width 2
bspc config normal_border_color "#32344a"
bspc config focused_border_color "#787c99"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

